apiDir: "../student-details-api/src/main/java"
apiPackagePath: "com.liferay.student.details"
application:
  baseURI: "/student"
  className: "StudentDetails"
  name: "student.details"
author: "Bhargav"
