components:
  schemas:
    Student:
      properties:
        studentName:
          type: string
        studentAddress:
          type: string
        studentId:
          type: integer
      type: object
info:
  description: >-
    A Java client JAR is available for use with the group ID 'com.liferay',
    artifact ID 'com.liferay.bulk.rest.client', and version '2.0.2'.
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  title: ''
  version: v1.0
openapi: 3.0.1
paths:
  /student:
    get:
      operationId: getStudent
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
            application/xml:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
servers:
  - url: 'http://localhost:8080/o/student'
    description: Local environment
